var lang_data = {
  "Palletization unit": "Palletization unit",
  "Variant": "Variant",
  "Count on pallet": "Count on pallet",
  "Active pallet": "Active pallet",
  "Set active left": "Set active left",
  "Left pallet placed": "Left pallet placed",
  "Set active right": "Set active right",
  "Right pallet placed": "Right pallet placed",
  "Count on pallet": "Count on pallet",
  "Reset counter": "Reset counter",
  "Setup left": "Setup left",
  "Reset left": "Reset left",
  "Setup right": "Setup right",
  "Reset right": "Reset right",
  "Variant 1": "Variant 1",
  "Variant 2": "Variant 2",
  "Variant 3": "Variant 3",
  "Variant 4": "Variant 4",
  "Variant 5": "Variant 5",
  "Variant 6": "Variant 6",
  "Variant 7": "Variant 7",
  "Variant 8": "Variant 8",
  "version": "ver 1.0"
}
